site_name: EPFL Flaked
nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: config.md
  - API: api.md
theme:
  name: material
repo_url: https://github.com/EPFL-ENAC/limnc-flaked
plugins:
  - search
